// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpe3ThdfV8lAfhRV15cBI1eQLssSpw670',
    appId: '1:864045743277:web:614c80dcdef7d76ba91a24',
    messagingSenderId: '864045743277',
    projectId: 'burnboss-ddb5b',
    authDomain: 'burnboss-ddb5b.firebaseapp.com',
    storageBucket: 'burnboss-ddb5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkvgGXgOhnrwAWyAL9Rgzo7DCqJTQYxio',
    appId: '1:864045743277:android:dbb369976b6540eea91a24',
    messagingSenderId: '864045743277',
    projectId: 'burnboss-ddb5b',
    storageBucket: 'burnboss-ddb5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8QuOfOf5QnYQJQuUbC_q6SHDJnmAhto',
    appId: '1:864045743277:ios:cb9539b18c1fd166a91a24',
    messagingSenderId: '864045743277',
    projectId: 'burnboss-ddb5b',
    storageBucket: 'burnboss-ddb5b.appspot.com',
    iosBundleId: 'BurnBoss.co.uk.burnboss',
  );
}
